apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy734
  labels:
    app: autodeploy734
  namespace: namespace-workflow-1709211621352
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy734
  template:
    metadata:
      labels:
        app: autodeploy734
    spec:
      containers:
        - name: autodeploy734
          image: acrworkflow1709211621352.azurecr.io/image-workflow-1709211621352:latest
          ports:
            - containerPort: 5000